/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NAToa0L3GET
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div
      className="flex flex-col items-center justify-center w-full min-h-screen bg-gradient-to-br from-[#d0e9f2] to-[#e8f0f5] px-4 py-8 sm:px-6 md:px-8 lg:px-12 xl:px-16">
      <Card className="w-full max-w-md rounded-2xl shadow-lg bg-white">
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Discover Your Khodam</CardTitle>
          <CardDescription>Enter your name to learn about your spiritual guardian.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4 p-6 sm:p-8">
          <div>
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <Button className="w-full">Reveal My Khodam</Button>
        </CardContent>
      </Card>
      <div className="mt-8 w-full max-w-3xl">
        <Card
          className="rounded-2xl shadow-lg bg-white p-6 sm:p-8 md:p-10 lg:p-12 xl:p-14">
          <CardHeader>
            <CardTitle className="text-2xl font-bold">What is a Khodam?</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-muted-foreground">
            <p>
              A khodam is a spiritual guardian or protector that is believed to be assigned to an individual at birth.
              Khodams are thought to possess unique characteristics and strengths that can guide and support the person
              throughout their life.
            </p>
            <p>
              Nurturing a relationship with your khodam can bring balance, clarity, and spiritual growth. By
              understanding the nature of your khodam, you can learn to harness its power and work in harmony with your
              spiritual guardian.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}
